export const OPEN_ROOM = 'OPEN_ROOM';
export const SET_ROOM_DETAILS = 'SET_ROOM_DETAILS';
export const SET_ACTIVE_ROOMS = 'SET_ACTIVE_ROOMS';
export const SET_LOCAL_STREAM = 'SET_LOCAL_STREAM';
export const SET_REMOTE_STREAMS = 'SET_REMOTE_STREAMS';
export const SET_AUDIO_ONLY = 'SET_AUDIO_ONLY';
export const SET_SCREEN_SHARE_STREAM = 'SET_SCREEN_SHARE_STREAM';
export const SET_IS_USER_JOINED_WITH_ONLY_AUDIO = 'SET_IS_USER_JOINED_WITH_ONLY_AUDIO';
